import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Menu } from "@/components/menu/Menu";
import SmoothScrolling from "@/components/SmoothScrolling";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SmoothScrolling>
        <Menu />
        <main>
          {children}
          </main>
          </SmoothScrolling>
      </body>

    </html>
  );
}
